trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  version: 1.0.$(Build.BuildId)

stages:
- stage: Build_Stage
  displayName: 
  jobs:
  - job: BuildNuget
    displayName: Build Nuget packages
    variables:
      BuildConfiguration: release
    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET 6 SDK'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        includePreviewVersions: true

    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages'
      inputs:
        restoreSolution: '$(solution)'

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        arguments: --no-restore --configuration $(buildConfiguration) 
        publishTestResults: false
        projects: '**/*.UnitTests.csproj'
        testRunTitle: 'Unit-Test-Run-$(Build.BuildId)'

    - task: DotNetCoreCLI@2
      displayName: Build Apps
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Pack Nuget Package
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        nobuild: true
        versioningScheme: byEnvVar
        versionEnvVar: 'version'

    - task: DotNetCoreCLI@2
      displayName: Push Nuget Package
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        versioningScheme: byEnvVar
        versionEnvVar: 'version'
        publishVstsFeed: 'emilfilip3'
        allowPackageConflicts: true